# Fork Sync Protection Configuration
# This file centralizes all protection settings for the fork sync monitoring workflow

# Protected directories and files that should be monitored for conflicts
protected_paths:
  - "specs/auto-accept-countdown/"
  - ".claude/commands/"
  - "examples/hooks/"

# Critical files that must exist for feature integrity
critical_files:
  - "specs/auto-accept-countdown/requirements.md"
  - "specs/auto-accept-countdown/design.md"
  - "specs/auto-accept-countdown/tasks.md"
  - "specs/auto-accept-countdown/INSTALLATION_GUIDE.md"
  - "specs/auto-accept-countdown/IMPLEMENTATION_COMPLETE.md"
  - "specs/auto-accept-countdown/install.js"
  - "specs/auto-accept-countdown/src/countdown-timer.ts"
  - "specs/auto-accept-countdown/src/auto-accept-interceptor.ts"
  - ".claude/commands/timer.md"
  - ".claude/commands/countdown.md"

# Fork-specific URL patterns that should be preserved
fork_specific_urls:
  - pattern: "bizzkoot/TimerCC"
    description: "Primary fork repository reference"
  - pattern: "claude-pause"
    description: "Fork-specific project name"
  - pattern: "bizzkoot"
    description: "Fork owner reference"

# Upstream repository configuration
upstream:
  owner: "anthropics"
  repo: "claude-code"
  main_branch: "main"

# Monitoring configuration
monitoring:
  # Minimum count of fork-specific URLs that should exist
  min_fork_url_count: 2
  
  # Maximum time in minutes for workflow execution
  max_execution_time: 10
  
  # Days to wait before considering a duplicate comment "old enough"
  duplicate_comment_age_days: 3

# Auto-merge settings
auto_merge:
  # Enable automatic merging for safe changes
  enabled: true
  
  # Paths that if changed upstream require manual review
  manual_review_paths:
    - "specs/auto-accept-countdown/"
    - ".claude/commands/timer.md"
    - ".claude/commands/countdown.md"
    - "examples/hooks/"
  
  # File extensions that are considered safe for auto-merge
  safe_extensions:
    - ".md"
    - ".yml"
    - ".yaml"
    - ".json"
  
  # Exclude certain documentation files from auto-merge
  exclude_from_auto_merge:
    - "CHANGELOG.md"
    - "README.md"

# PR generation settings
pr_generation:
  # Template for complex change PRs
  title_template: "🔄 Upstream sync: Complex changes detected"
  
  # Labels to apply to generated PRs
  labels:
    - "upstream-sync"
    - "needs-review"
    - "auto-generated"
  
  # Reviewers to request (GitHub usernames)
  reviewers:
    - "bizzkoot"